services:
  deltabook-db:
    image: timescale/timescaledb-ha:pg18
    container_name: deltabook-db
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "54329:5432"
    volumes:
      - deltabook-db-data:/home/postgres/pgdata

volumes:
  deltabook-db-data:
    driver: local
